"""initial

Revision ID: 72939162bdf0
Revises: 
Create Date: 2019-02-06 01:25:53.023071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72939162bdf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
